version: 2
updates:
  # NuGet config for SmallsOnline.WindowsBuildNumbers.Lib
  - package-ecosystem: "nuget"
    directory: "/src/SmallsOnline.WindowsBuildNumbers.Lib"
    target-branch: "main"
    schedule:
      interval: "daily"
    labels:
      - "dependency update"
    assignees:
      - "Smalls1652"

  # NuGet config for SmallsOnline.WindowsBuildNumbers.Lib.Benchmark
  - package-ecosystem: "nuget"
    directory: "/src/SmallsOnline.WindowsBuildNumbers.Lib.Benchmark"
    target-branch: "main"
    schedule:
      interval: "daily"
    labels:
      - "dependency update"
    assignees:
      - "Smalls1652"
  
  # NuGet config for SmallsOnline.WindowsBuildNumbers.Pwsh
  - package-ecosystem: "nuget"
    directory: "/src/SmallsOnline.WindowsBuildNumbers.Pwsh"
    target-branch: "main"
    schedule:
      interval: "daily"
    labels:
      - "dependency update"
    assignees:
      - "Smalls1652"
  
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"
    labels:
      - "dependency update"
    assignees:
      - "Smalls1652"